refactor: replaced wait instruction with serviceConfig.readyConditions config
kurtosis-tech/eth-network-package pull request #19
Opened 2023-05-15 20:09 UTC by leoporoli

2023-05-15 20:23 UTC, adschwartz commented on src/cl/cl_node_ready_conditions.star
> +        target_value = [200, 206, 503],
Did you mean to leave `503` in here? If so why would that be considered a valid "ready code"?

2023-05-15 20:24 UTC, adschwartz requested changes
@leoporoli looks good, but not sure about that `503` in the ready condition

2023-05-16 13:15 UTC, leoporoli commented
> @leoporoli looks good, but not sure about that `503` in the ready condition
now it's fixed, more context in this comment: https://github.com/kurtosis-tech/eth-network-package/pull/19#discussion_r1194366600

2023-05-16 17:14 UTC, leoporoli commented
@adschwartz don't forget this guy

2023-05-16 17:30 UTC, adschwartz approved these changes

2023-05-16 17:32 UTC, merged